---
# Vytvoření dedikovaného API uživatele s vysokým oprávněním pro potřeby Grafany
- name: Create a new Zabbix user
  community.zabbix.zabbix_user:
    username: "{{ zabbix_api_user }}"
    passwd: "{{ zabbix_api_user_password }}"
    role_name: "Super admin role"
    usrgrps:
      - "Zabbix administrators"
    state: present

    - name: Create user odvarkas
  community.zabbix.zabbix_user:
    username: odvarkas
    name: Štěpán
    surname: Odvárka
    passwd: "22Heslo74"
    role_name: "User role"
    usrgrps:
      - "Zabbix administrators"
    user_medias:
      - mediatype: Email
        sendto: "odvarka.stepan@student.sposdk.cz"
        active: 0
    state: present
